version: '3'

services:

    sample:
        build:
            context: .
            args:
                APP_HOME: src
                APP_NAME: go-sample
                APP_PORT: ${APP_PORT:-8010}
        ports:
            - "8010:${APP_PORT:-8010}"
        